inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Enabled: false

Layout/LeadingCommentSpace:
  Exclude:
    - '**/*.ru'
Layout/LineLength:
  Max: 125
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Exclude:
    - lib/api_valve/middleware/logging.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/api_valve/middleware/logging.rb
Metrics/BlockLength:
  Exclude:
    - '**/*.ru'

Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()
