MssqlA = Class.new(ActiveRecord::Base)
MssqlB = Class.new(ActiveRecord::Base)
MysqlA = Class.new(ActiveRecord::Base)
MysqlB = Class.new(ActiveRecord::Base)
ModelPostgres = Class.new(ActiveRecord::Base)
