require: rubocop-rspec
inherit_from: ../.rubocop.yml

Lint/UnneededCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
