inherit_from:
  - .rubocop_todo.yml
  - ../.rubocop.yml

require: rubocop-rspec


Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
