name: Push & PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: mysql-7.0
      - name: Rubocop
        run: bundle exec rubocop

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activerecord: ['6.1', '7.0']
        ruby: ['2.7', '3.0', '3.1', '3.2']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password1234
        ports:
          - 1433:1433
    env:
      BUNDLE_WITH: mysql sqlserver
      MYSQL_URL: mysql2://root@127.0.0.1:3306/test
      RAILS: ${{ matrix.activerecord }}
      RAILS_ENV: test
      SQLSERVER_URL: sqlserver://sa:Password1234@127.0.0.1:1433/test
    steps:
      - name: Create test DB
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE DATABASE IF NOT EXISTS test;"
      - name: Setup FreeTDS
        run: |
          sudo apt-get install -y freetds-bin freetds-common freetds-dev libct4 libsybdb5
      - name: Wait for SQLServer
        run: |
          until echo -e "SELECT @@VERSION\nGO" | tsql -H 127.0.0.1 -p 1433 -U sa -P Password1234;
          do
            echo 'Waiting for SqlServer ...'
            sleep 2
          done
      - name: Create test DB
        run: echo -e "CREATE DATABASE test\nGO" | tsql -H 127.0.0.1 -p 1433 -U sa -P Password1234
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: ${{ matrix.activerecord }}
      - name: RSpec
        run: bundle exec rspec
